name: Check and Deploy (Every 30 Minutes)

on:
  schedule:
    - cron: "0,30 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if service is up
        run: |
          RESPONSE=$(curl \
            --write-out "%{http_code}" \
            --silent \
            --output /dev/null \
            "https://telegrambotchiesaavventistatorino.onrender.com/")

          if [ "$RESPONSE" -ne 200 ]; then
            echo "Il servizio non è attivo. Avvio il deploy."
          else
            echo "Il servizio è attivo. Non è necessario il deploy."
            exit 0
          fi

      - name: Deploy to Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"